# Generated by Django 2.2 on 2020-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todobucket', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
